/**
 * CARTEL REST API
 * Barbershop CARTEL's REST API
 *
 * OpenAPI spec version: 1.0
 * Contact: #
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {DayReportModel} from './day.report.model';


export class BarberReportModel {
    barberId?: number;
    days?: DayReportModel[];
}
