/**
 * CARTEL REST API
 * Barbershop CARTEL's REST API
 *
 * OpenAPI spec version: 1.0
 * Contact: #
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {AppointmentReportModel} from './appointmentReportModel';


export class DayReportModel {
  date?: Date;
  appointments?: AppointmentReportModel[];
}
