create table barbers
(
	id bigint generated by default as identity
		constraint barbers_pkey
			primary key,
	description varchar(255),
	facebook varchar(255),
	first_name varchar(255),
	instagram varchar(255),
	last_name varchar(255),
	picture text
);

alter table barbers owner to cartel;

create table clients
(
	id bigint generated by default as identity
		constraint clients_pkey
			primary key,
	email varchar(255)
		constraint uk_srv16ica2c1csub334bxjjb59
			unique,
	phone_number varchar(255),
	username varchar(255)
);

alter table clients owner to cartel;

create table email_details
(
	id bigint generated by default as identity
		constraint email_details_pkey
			primary key,
	email_type integer,
	email_from varchar(255),
	language integer,
	subject varchar(255),
	text varchar(255)
);

alter table email_details owner to cartel;

create table general_configuration
(
	id bigint generated by default as identity
		constraint general_configuration_pkey
			primary key,
	address varchar(255),
	appointment_success_message varchar(255),
	city varchar(255),
	front_page_message varchar(255),
	language integer,
	phone_number varchar(255)
);

alter table general_configuration owner to cartel;

create table products
(
	id bigint generated by default as identity
		constraint products_pkey
			primary key,
	description varchar(255),
	price integer,
	title varchar(255)
);

alter table products owner to cartel;

create table product_details
(
	id bigint generated by default as identity
		constraint product_details_pkey
			primary key,
	picture text,
	product_id bigint
		constraint fknfvvq3meg4ha3u1bju9k4is3r
			references products
);

alter table product_details owner to cartel;

create table schedule_config
(
	id bigint generated by default as identity
		constraint schedule_config_pkey
			primary key,
	date date,
	first_appointment time,
	last_appointment time,
	working_day boolean,
	barber_id bigint
		constraint fkenj3ycbe3y03dm72npprx42d9
			references barbers
);

alter table schedule_config owner to cartel;

create table services
(
	id bigint generated by default as identity
		constraint services_pkey
			primary key,
	description varchar(255),
	picture text,
	service_title varchar(255)
);

alter table services owner to cartel;

create table appointments
(
	id bigint generated by default as identity
		constraint appointments_pkey
			primary key,
	date date,
	duration integer,
	end_time time,
	price integer,
	start_time time,
	barber_id bigint
		constraint fkicx8irhh8pdyhcogevp8a5l7j
			references barbers,
	client_id bigint
		constraint fkfbl6cciquyyvv5s1e31qmflkb
			references clients,
	service_id bigint
		constraint fk5iltr7k9pows18hk8nc101vc1
			references services
);

alter table appointments owner to cartel;

create table assignments
(
	id bigint generated by default as identity
		constraint assignments_pkey
			primary key,
	duration integer,
	price integer,
	barber_id bigint
		constraint fkluxmh20llav85a78jf5i300ds
			references barbers,
	service_id bigint
		constraint fk2wthk43akxxb5vemxty03hs6
			references services
);

alter table assignments owner to cartel;

create table users
(
	id bigint generated by default as identity
		constraint users_pkey
			primary key,
	email varchar(255) not null
		constraint uk_6dotkott2kjsp8vw4d0m25fb7
			unique,
	password varchar(255)
);

alter table users owner to cartel;

create table social_media
(
    id        bigint generated by default as identity
        constraint social_media_pkey
            primary key,
    facebook  varchar(255),
    instagram varchar(255)
);

alter table social_media
    owner to cartel;