create table work_day
(
    id        bigint generated by default as identity
        constraint work_day_pkey
            primary key,
    day       date,
    time_from time,
    all_day   boolean,
    time_to   time,
    barber_id bigint
        constraint fkk4ngeuq5jikxy0k3822ql7kpe
            references barbers
);

alter table work_day
    owner to cartel;