create table work_week_days
(
    id          bigint generated by default as identity
        constraint work_week_days_pkey
            primary key,
    day_of_week integer,
    time_from   time,
    not_working boolean,
    time_to     time,
    barber_id   bigint
        constraint fk67aemr8kxxkmy7dti2aff1uf9
            references barbers
);

alter table work_week_days
    owner to cartel;
